### ISSUE TITLE
Do not open epub files downloaded from Gutenberg

### ISSUE THREAD

**Issue by mattirn** [rschroll/beru#80]
Do not open any epub files downloaded from Gutenberg -claims that book is not drm-free.
Application works correctly if epub files are downloaded from MobileRead.
I'm using the BQ Aquaris E4.5 Ubuntu Edition.
Beru version: 1.0.0

**Comment by rschroll** [comment]
Unfortunately, this is due to a bug in the Download Manager 
(https://bugs.launchpad.net/ubuntu-download-manager/+bug/1384421).  
This results in it downloading a HTML page, not the epub file.

When I reported this, I got the impression that it would be relatively 
easy to fix.  However, it's been nearly six months with no action now.  
Frustrating, but there's not much I can do about it.

If this isn't fixed for the next release of Beru, I'll remove the link 
to Project Gutenberg.

**Comment by mattirn** [comment]
I see, in theory we can try to speed up fix by rising bug heat by logging launchpad.net and click affects me too link and subscribe the notifications of the bug.
https://bugs.launchpad.net/ubuntu-download-manager/+bug/1384421/+affectsmetoo

**Comment by rschroll** [comment]
It can't hurt!

**Comment by rschroll** [comment]
I've just committed a change that removes the whole built-in browser and downloader.  Now, it launches the system browser, which can import downloaded files via the content hub.  This seems to work with Project Gutenberg, so I'll close this bug for now.
