### ISSUE TITLE
Beru no longer opens on Ubuntu Touch devel-proposed (15.10) r205 and r206

### ISSUE THREAD

**Issue by BryWilson** [rschroll/beru#86]
As of yesterday, updated OTA devel-proposed (15.10) to r205 and Beru no longer opens. The "Library" page pops up with the spinning circle and then closes back to the Apps Scope.

Updating to r206 did not solve the problem, nor reinstalling Beru.

**Comment by UbuntuForumsCouncil** [comment]
can confirm that

**Comment by elfyesq** [comment]
they can't - I will though

**Comment by rschroll** [comment]
Thanks for the report.  Does it ever display any covers, or does it 
crash before that?

There may be logs saved as 
~/.cache/upstart/application-click-com.ubuntu.developer.rschroll.beru_beru*. 
 If you have some and care share the end of the most recent one, that 
may shed some light on what's happening.

If you want to help troubleshoot, the first thing to do is to try to 
run beru under gdb and get a stack trace.  Unfortunately, the trick I 
know for doing this no longer works.  I'll see if I can get it working, 
but if you know how, please speak up.

**Comment by elfyesq** [comment]
The last upstart log I have is

libust[4807/4810]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[4807/4810]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
Loading module: 'libubuntu_application_api_touch_mirclient.so.2.9.0'
/usr/lib/arm-linux-gnueabihf/qt5/bin/qmlscene: invalid option -- 'I'
/usr/lib/arm-linux-gnueabihf/qt5/bin/qmlscene: unrecognized option '--appargs='
[1432331092.772561] Loader: Loading modules from: /usr/lib/arm-linux-gnueabihf/mir/client-platform/
[1432331092.773355] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/mesa.so.2
[1432331092.774546] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/android.so.2
[1432331092.776134] Loader: Loading module: /usr/lib/arm-linux-gnueabihf/mir/client-platform/dummy.so
libust[4807/4830]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[4807/4830]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[4807/4831]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
libust[4807/4831]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wait_shm() at lttng-ust-comm.c:958)
shm_open() failed: Permission denied
Failed to create secure directory (/run/user/32011/pulse): Permission denied
[0522/224455:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[0522/224455:WARNING:proxy_service.cc(899)] PAC support disabled because there is no system implementation
<Unknown File>: QML UCDeprecatedTheme: Theme.palette is deprecated. Use ThemeSettings instead.
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Content/ContentPeerPicker11.qml:48:5: QML Header: Theme.createStyleComponent() is deprecated. Use ThemeSettings instead.
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/Themes/Ambiance/1.2/PageHeadStyle.qml:86:5: QML StyledItem: Theme.createStyleComponent() is deprecated. Use ThemeSettings instead.
file:///opt/click.ubuntu.com/com.ubuntu.developer.rschroll.beru/1.1.0/ui/Importer.qml:159:9: QML Scrollbar: Theme.createStyleComponent() is deprecated. Use ThemeSettings instead.
file:///opt/click.ubuntu.com/com.ubuntu.developer.rschroll.beru/1.1.0/ui/BookPage.qml:64:5: QML ActivityIndicator: Theme.createStyleComponent() is deprecated. Use ThemeSettings instead.

**Comment by elfyesq** [comment]
mmm - didn't do more than paste the log ... 

I see exactly the same as  BryWilson - The "Library" page pops up with the spinning circle and then closes back to the Apps Scope.

**Comment by elfyesq** [comment]
updated to r207. Still the same issue.

**Comment by rschroll** [comment]
Thanks.  No obvious problems in those logs.  I'll see if I can get 
instructions for gdb.

**Comment by BryWilson** [comment]
Apologies for not following up on my original posting - but I've just returned from overseas and updated OTA devel-proposed (15.10) to r248 - and Beru seems to working absolutely fine now. Any ideas what might have changed?

**Comment by UbuntuForumsCouncil** [comment]
The contact us link you used to send your email is for contacting forum
admins regarding problems with your forum account. We cannot provide
technical support from the mailing list.

If you need help from forum members, please go to a sub-forum that is
relevant - I suggest the Ubuntu Phone and Tablet
<http://ubuntuforums.org/forumdisplay.php?f=460>. Click on the orange Post
New Thread button to post your question.

slickymaster
Ubuntu Forums Council

**Comment by rschroll** [comment]
No idea, I'm afraid.  I assume they broke, and then fixed, something in 
devel-proposed.  I don't follow that channel, so I don't know what.

@elfyesq: Is it working for you now or not?

**Comment by UbuntuForumsCouncil** [comment]
Please do not send emails concerning this Beru Ubuntu Touch github 
conversation to the Forum Council mailing list - 
ubuntu-forums-council@lists.ubuntu.com. The Forum Council mailing list 
is for matters concerning the Ubuntu Forums governance, and for forum 
members to contact admins for help with their forum account.

Elfy, known to you as elfyesq, is no longer on the Forum Council

Coffeecat (for Forum Council)

**Comment by rschroll** [comment]
On Tue, Jul 7, 2015 at 12:00 PM, UbuntuForumsCouncil 
<notifications@github.com> wrote:
> Please do not send emails concerning this Beru Ubuntu Touch github
> conversation to the Forum Council mailing list

Then please do not register to receive notifications about this issue.  
There are several ways in which you could do this:

1) You could not use the Forum Council mailing list as your Github 
account's email.

2) You could not use this account to comment on Github issues.

3) You could set up your Github account to not receive email 
notifications about issue updates.

4) You could hit the "Unsubscribe" button on the Github issue page, now 
that you've not done (1), (2), or (3).

Note that none involves badgering me.

**Comment by elfyesq** [comment]
The FC didn't. I think I possibly did by posting once as the FC github account. I did delete that posting. 

As far as the issue with Beru is concerned - I removed Ubuntu Touch so have no idea. 

I've deleted my github account - so hopefully that should stop any spurious postings to the FC.

**Comment by rschroll** [comment]
Yeah, that's not going to do anything.  But since no one seems to be experiencing this bug anymore, I'll go ahead and close it.
